### ISSUE TITLE
How is title working?

### ISSUE THREAD

**Issue by IGraysonI** [Mayb3Nots/flutter_audio_query#1]
Hello there. Thanks for transferring this to null-safety. I looked through the code i couldn't find how the `title ` attribute of SongInfo works. I want to see how it getting `title` tag from music file to add functionality to get other tag's, especially `lyrics ` from music file.. Could you lend me a hand and say how the `title` is getting title?

**Comment by Mayb3Nots** [comment]
Hi sorry for the late reply, I seemed to have overlooked this. It seemed like you already found out a way to get the `lyrics` from the map. So im gonna close this.
